version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: myapp_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db-migration:
    image: "amacneil/dbmate:2.17"
    restart: "on-failure"
    volumes:
      - ./:/myapp
    working_dir: /myapp
    depends_on:
      postgres:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/myapp?sslmode=disable
      - DBMATE_MIGRATIONS_DIR=/myapp/resources/pgsql/migrations
      - DBMATE_NO_DUMP_SCHEMA=true
      - DBMATE_VERBOSE=true
      - DBMATE_STRICT=true
      - DBMATE_WAIT=true
      - DBMATE_WAIT_TIMEOUT=60s
    command: up

  adminer:
    image: adminer:latest
    depends_on:
      postgres:
        condition: service_started
    ports:
      - "9000:8080"
    
volumes:
  postgres_data: